import os, random
import pikepdf
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, A0
from reportlab.lib.colors import HexColor, white, black

# Corpus of problematic PDFs (fixtures/pdfs). The >3.5 MB file is generated by the tests themselves.
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'fixtures', 'pdfs')
os.makedirs(OUT, exist_ok=True)
P = lambda n: os.path.join(OUT, n)

def simple(path, pages=2):
    c = canvas.Canvas(path, pagesize=A4)
    for p in range(pages):
        c.setFont('Helvetica', 14); c.drawString(72, 760, f'Hello Folio page {p+1} normal text')
        c.setFont('Times-Bold', 18); c.drawString(72, 720, 'Serif bold heading')
        # dark header band with white text
        c.setFillColor(HexColor('#1f3a5f')); c.rect(0, 600, 595, 60, fill=1, stroke=0)
        c.setFillColor(white); c.setFont('Helvetica-Bold', 20); c.drawString(72, 622, 'White on dark blue')
        # light gray box
        c.setFillColor(HexColor('#eeeeee')); c.rect(60, 480, 300, 50, fill=1, stroke=0)
        c.setFillColor(HexColor('#cc0000')); c.setFont('Courier', 12); c.drawString(72, 500, 'Red mono on gray')
        c.setFillColor(black); c.setFont('Helvetica', 11)
        c.drawString(72, 400, 'Name: ______________________')
        c.drawString(72, 370, 'Date: ......................')
        c.showPage()
    c.save()

simple(P('01_simple.pdf'))

# The > 3.5 MB PDF (sessionStorage quota case) is generated by the tests: lib/helpers.js bigPdf()

# encrypted variants
src = pikepdf.open(P('01_simple.pdf'))
src.save(P('03_enc_owner_aes256.pdf'), encryption=pikepdf.Encryption(owner='owner', user='', R=6, allow=pikepdf.Permissions(modify_other=False, extract=False)))
src.save(P('04_enc_owner_rc4.pdf'), encryption=pikepdf.Encryption(owner='owner', user='', R=3, aes=False, metadata=False))
src.save(P('05_enc_owner_aes128.pdf'), encryption=pikepdf.Encryption(owner='owner', user='', R=4, aes=True))
src.save(P('06_enc_user_pw.pdf'), encryption=pikepdf.Encryption(owner='owner', user='test', R=4, aes=True))
src.close()

# garbage prefix
data = open(P('01_simple.pdf'), 'rb').read()
open(P('07_garbage_prefix.pdf'), 'wb').write(b'\r\n<html>junk before header</html>\r\n' * 20 + data)

# broken xref offsets
s = data
idx = s.rfind(b'xref')
tail = s[idx:]
import re
tail2 = re.sub(rb'(\d{10}) 00000 n', lambda m: b'%010d 00000 n' % (int(m.group(1)) + 37), tail)
open(P('08_broken_xref.pdf'), 'wb').write(s[:idx] + tail2)

# truncated (no trailer/xref)
open(P('09_truncated.pdf'), 'wb').write(data[:int(len(data)*0.93)])

# rotated + cropbox offset
pdf = pikepdf.open(P('01_simple.pdf'))
pdf.pages[0].Rotate = 90
pdf.pages[1].MediaBox = [-50, -50, 700, 900]
pdf.pages[1].CropBox = [30, 100, 560, 800]
pdf.save(P('10_rotated_cropbox.pdf'))

# object streams / xref streams
pdf = pikepdf.open(P('01_simple.pdf'))
pdf.save(P('11_objstreams.pdf'), object_stream_mode=pikepdf.ObjectStreamMode.generate)

# AcroForm with text/checkbox/radio/choice
c = canvas.Canvas(P('12_form.pdf'), pagesize=A4)
f = c.acroForm
c.setFont('Helvetica', 12)
c.drawString(72, 760, 'First name:'); f.textfield(name='first_name', x=160, y=750, width=200, height=20, borderStyle='inset', forceBorder=True)
c.drawString(72, 720, 'Agree:'); f.checkbox(name='agree', x=160, y=715, size=16, buttonStyle='check')
c.drawString(72, 680, 'Choice:')
f.radio(name='color', value='red', x=160, y=675, size=14, selected=False)
f.radio(name='color', value='blue', x=200, y=675, size=14, selected=False)
c.drawString(72, 640, 'Country:'); f.choice(name='country', options=['France', 'Belgium', 'Canada'], value='France', x=160, y=632, width=150, height=20)
c.drawString(72, 600, 'Comments:'); f.textfield(name='comments', x=160, y=540, width=300, height=60, fieldFlags='multiline')
c.showPage(); c.save()

# form field missing /DA (pdf-lib save crash case)
pdf = pikepdf.open(P('12_form.pdf'))
for fld in pdf.Root.AcroForm.Fields:
    if '/DA' in fld: del fld['/DA']
if '/DA' in pdf.Root.AcroForm: del pdf.Root.AcroForm['/DA']
pdf.save(P('13_form_no_DA.pdf'))

# Large format page (A0) — canvas size limits
c = canvas.Canvas(P('14_a0.pdf'), pagesize=A0)
c.setFont('Helvetica', 60); c.drawString(200, 3000, 'Huge A0 poster')
c.showPage(); c.save()

# Uppercase extension copy
open(P('15_UPPER.PDF'), 'wb').write(data)

# Missing EOF + extra trailing junk
open(P('16_trailing_junk.pdf'), 'wb').write(data + b'\n' + os.urandom(3000))

# PDF 1.7 with broken /Pages kid ref (corrupt page tree)
pdf = pikepdf.open(P('01_simple.pdf'))
pdf.save(P('17_tmp.pdf'), qdf=True, static_id=True, object_stream_mode=pikepdf.ObjectStreamMode.disable, compress_streams=False)
raw = open(P('17_tmp.pdf'), 'rb').read()
os.remove(P('17_tmp.pdf'))
# break the Pages reference in the catalog to a missing object
m = re.search(rb'/Pages (\d+) 0 R', raw)
raw2 = raw.replace(m.group(0), b'/Pages 999 0 R', 1)
open(P('17_corrupt_pagetree.pdf'), 'wb').write(raw2)

for n in sorted(os.listdir(OUT)):
    print(f'{n:32s} {os.path.getsize(P(n)):>10d}')
