// api/consume.js
// POST /api/consume  { uid: string }
// Returns: { ok: true, creditsLeft: number } or { ok: false, reason: 'no_credits' }
// Logic:
//   - UID must already exist (created by /api/status on first load) — no auto-create here
//   - If free_used = false → allow, set free_used = true
//   - Else if credits > 0  → allow, credits -= 1
//   - Else                 → deny
//
// Security hardening vs original:
//   1. Unknown UIDs → no auto-create, return no_credits immediately
//      (closes the "forge a fresh UID → get infinite free sessions" bypass)
//   2. UID format validation — must match the pattern generated by payment.js
//      (rejects trivially crafted UIDs)
//   3. In-memory IP rate limiting — max MAX_PER_WINDOW calls per IP per window
//      (blunts scripted abuse without any external dependency)

// ── IP rate limiter (in-memory, resets on cold start) ────────────────────────
const MAX_PER_WINDOW = 5;       // max consume calls per IP per window
const WINDOW_MS      = 60_000;  // 1-minute sliding window
const ipHits         = new Map(); // ip → [timestamp, ...]

function isRateLimited(ip) {
  if (!ip) return false;
  const now  = Date.now();
  const hits = (ipHits.get(ip) || []).filter(t => now - t < WINDOW_MS);
  hits.push(now);
  ipHits.set(ip, hits);
  // Evict stale entries to avoid memory leak on long-lived instances
  if (ipHits.size > 5000) {
    for (const [k, v] of ipHits) {
      if (v.every(t => now - t >= WINDOW_MS)) ipHits.delete(k);
    }
  }
  return hits.length > MAX_PER_WINDOW;
}

// ── UID format validation ─────────────────────────────────────────────────────
// payment.js generates: 'u_' + Date.now().toString(36) + '_' + 8 random base36 chars
// Example: u_lzxw4khs_3f9ab2c1
const UID_RE = /^u_[0-9a-z]{6,12}_[0-9a-z]{6,12}$/;

function isValidUIDFormat(uid) {
  return typeof uid === 'string' && UID_RE.test(uid);
}

// ── Handler ───────────────────────────────────────────────────────────────────
export default async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // ── Rate limit by IP ──────────────────────────────────────────────────────
  const ip = req.headers['x-forwarded-for']?.split(',')[0].trim() || req.socket?.remoteAddress;
  if (isRateLimited(ip)) {
    return res.status(429).json({ ok: false, reason: 'rate_limited' });
  }

  let body;
  try {
    body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  } catch {
    return res.status(400).json({ error: 'Invalid JSON' });
  }

  const { uid } = body || {};

  // ── UID validation ────────────────────────────────────────────────────────
  // Return no_credits (not an error) → client shows payment modal, not a crash.
  // Never reveal why the UID was rejected.
  if (!uid || !isValidUIDFormat(uid)) {
    return res.status(200).json({ ok: false, reason: 'no_credits', creditsLeft: 0 });
  }

  try {
    const result = await tryConsume(uid);
    return res.status(200).json(result);
  } catch (e) {
    console.error('[consume]', e);
    return res.status(500).json({ error: 'Server error' });
  }
}

async function tryConsume(uid) {

  // ── Fetch user ────────────────────────────────────────────────────────────
  const getUrl =
    `${process.env.SUPABASE_URL}/rest/v1/users` +
    `?uid=eq.${encodeURIComponent(uid)}` +
    `&select=uid,credits,free_used,lifetime_free,edit_count`;

  const r = await fetch(getUrl, {
    headers: {
      'apikey':        process.env.SUPABASE_KEY,
      'Authorization': `Bearer ${process.env.SUPABASE_KEY}`
    }
  });

  if (!r.ok) throw new Error('Supabase fetch error');

  const rows = await r.json();

  // ── SECURITY: unknown UID → deny, do NOT auto-create ─────────────────────
  // UIDs are created by /api/status (called automatically on editor load).
  // If a UID arrives here that doesn't exist, it was forged — deny silently.
  if (rows.length === 0) {
    return { ok: false, reason: 'no_credits', creditsLeft: 0 };
  }

  const user = rows[0];

  // ── Lifetime free users ───────────────────────────────────────────────────
  if (user.lifetime_free === true) {
    await patchUser(uid, { edit_count: (user.edit_count || 0) + 1 });
    return { ok: true, creditsLeft: user.credits, usedLifetimeFree: true };
  }

  // ── First free use ────────────────────────────────────────────────────────
  if (!user.free_used) {
    await patchUser(uid, { free_used: true, edit_count: (user.edit_count || 0) + 1 });
    return { ok: true, creditsLeft: user.credits, usedFree: true };
  }

  // ── Consume paid credit ───────────────────────────────────────────────────
  if (user.credits > 0) {
    await patchUser(uid, { credits: user.credits - 1, edit_count: (user.edit_count || 0) + 1 });
    return { ok: true, creditsLeft: user.credits - 1, usedFree: false };
  }

  // ── No credits left ───────────────────────────────────────────────────────
  return { ok: false, reason: 'no_credits', creditsLeft: 0 };
}

async function patchUser(uid, patch) {
  const url = `${process.env.SUPABASE_URL}/rest/v1/users?uid=eq.${encodeURIComponent(uid)}`;
  await fetch(url, {
    method: 'PATCH',
    headers: {
      'apikey':        process.env.SUPABASE_KEY,
      'Authorization': `Bearer ${process.env.SUPABASE_KEY}`,
      'Content-Type':  'application/json',
      'Prefer':        'return=minimal'
    },
    body: JSON.stringify(patch)
  });
}
